# config/config.yml
development:
  userstore: demo #devise, local_db, or demo    
  user_store_url: http://userdome.heroku.com
  client_sites: #this is for logout on logout an iframe will be rendered for each of these
    - "http://casclientone.heroku.com"
    - 'http://casclienttwo.heroku.com'

  
production:
  userstore: devise
  redis_host: goosefish.redistogo.com
  redis_port: 9787
  redis_password: 60805d87e9dc1626bd64928253407933
  user_store_url: http://userdome.heroku.com
  client_sites: 
    - "http://casclientone.heroku.com"
    - 'http://casclienttwo.heroku.com'
